pub enum Keywords {
    Add,
    Sub,
    Mul,
    Div,
    Mod,
    And,
    Or,
    Concat,
    Neg,
    Sqrt,
    Sin,
    Cos,
    Tan,
    Abs,
    Floor,
    Ceil,
    Not,
    Len,
    Upper,
    Lower,
    Exit,
    Pow,
    Rand,
    Eq,
    Neq,
    Gt,
    Lt,
    Gte,
    Lte,
    Let,
    Del,
    If,
    Elif,
    Else,
    Switch,
    Case,
    Default,
    For,
    While,
    Function,
    Return,
    Break,
    Continue,
    Substring,
    Strip,
    Replace,
    Print
}

pub fn get_keyword(keyword: &str) -> Keywords {
    match keyword {
        "+" => Keywords::Add,
        "-" => Keywords::Sub,
        "*" => Keywords::Mul,
        "/" => Keywords::Div,
        "%" => Keywords::Mod,
        "&&" => Keywords::And,
        "||" => Keywords::Or,
        "<>" => Keywords::Concat,
        "~" => Keywords::Neg,
        "sqrt" => Keywords::Sqrt,
        "sin" => Keywords::Sin,
        "cos" => Keywords::Cos,
        "tan" => Keywords::Tan,
        "abs" => Keywords::Abs,
        "floor" => Keywords::Floor,
        "ceil" => Keywords::Ceil,
        "!" => Keywords::Not,
        "len" => Keywords::Len,
        "upper" => Keywords::Upper,
        "lower" => Keywords::Lower,
        "exit" => Keywords::Exit,
        "^" => Keywords::Pow,
        "rand" => Keywords::Rand,
        "==" => Keywords::Eq,
        "!=" => Keywords::Neq,
        ">" => Keywords::Gt,
        "<" => Keywords::Lt,
        ">=" => Keywords::Gte,
        "<=" => Keywords::Lte,
        "let" => Keywords::Let,
        "del" => Keywords::Del,
        "if" => Keywords::If,
        "elif" => Keywords::Elif,
        "else" => Keywords::Else,
        "switch" => Keywords::Switch,
        "case" => Keywords::Case,
        "default" => Keywords::Default,
        "for" => Keywords::For,
        "while" => Keywords::While,
        "func" => Keywords::Function,
        "return" => Keywords::Return,
        "break" => Keywords::Break,
        "continue" => Keywords::Continue,
        "substring" => Keywords::Substring,
        "strip" => Keywords::Strip,
        "replace" => Keywords::Replace,
        "print" => Keywords::Print,
        _ => panic!("Unknown keyword: {}", keyword),
    }
}